
models = {
  "openai-gpt":                   ("openai-community/openai-gpt",      "OpenAIGPTLMHeadModel"),
  "gpt2":                         ("openai-community/gpt2",            "GPT2LMHeadModel"),
  "gpt2-large":                   ("openai-community/gpt2-large",      "GPT2LMHeadModel"),
  "gemma-3-270m":                 ("google/gemma-3-270m",              "AutoModelForCausalLM"),
  "gemma-3-1b-pt":                ("google/gemma-3-1b-pt",             "Gemma3ForCausalLM"),
  "gemma-3-4b-pt":                ("google/gemma-3-4b-pt",             "Gemma3ForCausalLM"),
  "bloom-560m":                   ("bigscience/bloom-560m",            "BloomForCausalLM"),
  "bloom-1b7":                    ("bigscience/bloom-1b7",             "BloomForCausalLM"),
  "bloom-3b":                     ("bigscience/bloom-3b",              "BloomForCausalLM"),
  "xglm-564M":                    ("facebook/xglm-564M",               "XGLMForCausalLM"),
  "xglm-1.7B":                    ("facebook/xglm-1.7B",               "XGLMForCausalLM"),
  "xglm-2.9B":                    ("facebook/xglm-2.9B",               "XGLMForCausalLM"),
  "german-gpt2":                  ("dbmdz/german-gpt2",                "AutoModelForCausalLM"),
  "german-gpt2-larger":           ("stefan-it/german-gpt2-larger",     "AutoModelForCausalLM"),
  "gerpt2":                       ("benjamin/gerpt2",                  "AutoModelForCausalLM"),
  "gerpt2-large":                 ("benjamin/gerpt2-large",            "AutoModelForCausalLM"),
  "gpt2-chinese-cluecorpussmall": ("uer/gpt2-chinese-cluecorpussmall", "GPT2LMHeadModel"),
}
